server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/counter
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: validate
    show-sql: true

  application:
    name: CODE-GENERATOR
  config:
    import: optional:file:.env[.properties]
#    import: add you config here

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    baseline-description: "init"
    baseline-version: 0

